config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  resources :athletes
  resources :compulsory_figures
  resources :free_skates
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/compulsory_figure.rb
class CompulsoryFigure < ApplicationRecord
end

app/controllers/compulsory_figures_controller.rb
class CompulsoryFiguresController < ApplicationController
  before_action :set_compulsory_figure, only: [:show, :edit, :update, :destroy]

  # GET /compulsory_figures
  # GET /compulsory_figures.json
  def index
    @compulsory_figures = CompulsoryFigure.all
  end

  # GET /compulsory_figures/1
  # GET /compulsory_figures/1.json
  def show
  end

  # GET /compulsory_figures/new
  def new
    @compulsory_figure = CompulsoryFigure.new
  end

  # GET /compulsory_figures/1/edit
  def edit
  end

  # POST /compulsory_figures
  # POST /compulsory_figures.json
  def create
    @compulsory_figure = CompulsoryFigure.new(compulsory_figure_params)

    respond_to do |format|
      if @compulsory_figure.save
        format.html { redirect_to @compulsory_figure, notice: 'Compulsory figure was successfully created.' }
        format.json { render :show, status: :created, location: @compulsory_figure }
      else
        format.html { render :new }
        format.json { render json: @compulsory_figure.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /compulsory_figures/1
  # PATCH/PUT /compulsory_figures/1.json
  def update
    respond_to do |format|
      if @compulsory_figure.update(compulsory_figure_params)
        format.html { redirect_to @compulsory_figure, notice: 'Compulsory figure was successfully updated.' }
        format.json { render :show, status: :ok, location: @compulsory_figure }
      else
        format.html { render :edit }
        format.json { render json: @compulsory_figure.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /compulsory_figures/1
  # DELETE /compulsory_figures/1.json
  def destroy
    @compulsory_figure.destroy
    respond_to do |format|
      format.html { redirect_to compulsory_figures_url, notice: 'Compulsory figure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_compulsory_figure
      @compulsory_figure = CompulsoryFigure.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def compulsory_figure_params
      params.require(:compulsory_figure).permit(:description)
    end
end

app/helpers/compulsory_figures_helper.rb
module CompulsoryFiguresHelper
end

app/views/compulsory_figures/_form.html.erb
<!-- lib/templates/erb/scaffold/_form.html.erb.tt -->

<%= form_with(model: compulsory_figure) do |form| %>
  <%= render "error_messages", resource: form.object %>

  <div class="mb-6">

    <%= form.label :description, class: "label" %>
    <%= form.text_field :description, class: "input" %>

  </div>

  <div class="mb-6 flex justify-between items-center">
    <%= form.button class: "btn btn-primary" %>

    <% if form.object.persisted? %>
      <%= link_to 'Eliminar', form.object, class: "btn btn-danger", method: :delete, data: { remote: true, confirm: "Está seguro?" } %>
    <% end %>
  </div>
<% end %>

app/views/compulsory_figures/edit.html.erb
<!-- lib/templates/erb/scaffold/edit.html.erb.tt -->

<div class="container mx-auto my-8 px-4", aling="center">
  <div class="max-w-xl mx-auto">
    <h1 class="text-2xl font-bold mb-6">Editar Compulsory Figure</h1>

    <%= render 'form', compulsory_figure: @compulsory_figure %>
  </div>
</div>

app/views/compulsory_figures/index.html.erb
<!-- lib/ /erb/scaffold/index.html.erb.tt -->

<div class="container mx-auto my-8 px-4">
  <div class="flex justify-between items-center mb-4">
    <h1 class="text-2xl font-semibold">Compulsory Figures</h1>

    <% if @compulsory_figures.exists? %>
      <%= link_to 'Nuevo', new_compulsory_figure_path, class: "btn btn-success" %>
    <% end %>
  </div>

  <% if @compulsory_figures.exists? %>
    <div class="bg-white rounded shadow">
      <table class="w-full table-hover">
        <thead>
          <tr>
            <th class="p-3 uppercase text-left text-xs text-gray-700">Description</th>

            <th class="p-3 uppercase text-left text-xs text-gray-700">Actions</th>
          </tr>
        </thead>

        <tbody>
        <% @compulsory_figures.each do |compulsory_figure| %>
          <tr class="group border-t border-gray-400 hover:bg-gray-100">
                          <td class="p-3"><%= compulsory_figure.description %></td>
            
            <td>
              <%= link_to "Detalles", compulsory_figure, class: "btn btn-info" %>
              <%= link_to "Editar", edit_compulsory_figure_path(compulsory_figure), class: "btn btn-primary" %>
     	      <td><%= link_to 'Eliminar', compulsory_figure, class: "btn btn-danger" ,  method: :delete, data: { confirm: 'Está seguro?' } %></td>

            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

  <% else %>
    <div class="bg-white rounded shadow flex items-center justify-between p-8">
      <div class="flex-1 text-center", align="center">
        <p class="text-xl font-semibold mb-4"> Crea tu primera Compulsory Figure</p>
      <%= link_to 'Nuevo', new_compulsory_figure_path, class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/compulsory_figures/new.html.erb
<!-- lib/templates/erb/scaffold/new.html.erb.tt -->

<div class="container mx-auto my-8 px-4",aling="center">
  <div class="max-w-xl mx-auto">
    <h1 class="text-2xl font-bold mb-6">New Compulsory Figure</h1>
    <%= link_to '< Volver', compulsory_figures_path, class: "link" %></br></br>
    <%= render 'form', compulsory_figure: @compulsory_figure %>
  </div>
</div>

app/views/compulsory_figures/show.html.erb
<!-- lib/templates/erb/scaffold/show.html.erb.tt -->

<div class="container", aling="center">
<div class="card border-primary mb-3">
<div class="card">
  <div class="card-header">
    Detalles
  </div>
  <div class="card-body">
    <div class="container mx-auto my-8 px-4">
            <p class="text-lg font-semibold">Description:</p>
      <p class="leading-normal"><%= @compulsory_figure.description %></p>

            <div class="flex items-center justify-start mt-6">
        <%= link_to 'Editar', edit_compulsory_figure_path(@compulsory_figure), class: "btn btn-info mr-4" %>
        <%= link_to '< Volver', compulsory_figures_path, class: "btn btn-default" %>
      </div>
    </div>
    </div>
  </div>
  </div>