config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  resources :athletes
  resources :compulsory_figures
  resources :free_skates
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/free_skate.rb
class FreeSkate < ApplicationRecord
end

app/controllers/free_skates_controller.rb
class FreeSkatesController < ApplicationController
  before_action :set_free_skate, only: [:show, :edit, :update, :destroy]

  # GET /free_skates
  # GET /free_skates.json
  def index
    @free_skates = FreeSkate.all
  end

  # GET /free_skates/1
  # GET /free_skates/1.json
  def show
  end

  # GET /free_skates/new
  def new
    @free_skate = FreeSkate.new
  end

  # GET /free_skates/1/edit
  def edit
  end

  # POST /free_skates
  # POST /free_skates.json
  def create
    @free_skate = FreeSkate.new(free_skate_params)

    respond_to do |format|
      if @free_skate.save
        format.html { redirect_to @free_skate, notice: 'Free skate was successfully created.' }
        format.json { render :show, status: :created, location: @free_skate }
      else
        format.html { render :new }
        format.json { render json: @free_skate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /free_skates/1
  # PATCH/PUT /free_skates/1.json
  def update
    respond_to do |format|
      if @free_skate.update(free_skate_params)
        format.html { redirect_to @free_skate, notice: 'Free skate was successfully updated.' }
        format.json { render :show, status: :ok, location: @free_skate }
      else
        format.html { render :edit }
        format.json { render json: @free_skate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /free_skates/1
  # DELETE /free_skates/1.json
  def destroy
    @free_skate.destroy
    respond_to do |format|
      format.html { redirect_to free_skates_url, notice: 'Free skate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_free_skate
      @free_skate = FreeSkate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def free_skate_params
      params.require(:free_skate).permit(:description)
    end
end

app/helpers/free_skates_helper.rb
module FreeSkatesHelper
end

app/views/free_skates/_form.html.erb
<!-- lib/templates/erb/scaffold/_form.html.erb.tt -->

<%= form_with(model: free_skate) do |form| %>
  <%= render "error_messages", resource: form.object %>

  <div class="mb-6">

    <%= form.label :description, class: "label" %>
    <%= form.text_field :description, class: "input" %>

  </div>

  <div class="mb-6 flex justify-between items-center">
    <%= form.button class: "btn btn-primary" %>

    <% if form.object.persisted? %>
      <%= link_to 'Eliminar', form.object, class: "btn btn-danger", method: :delete, data: { remote: true, confirm: "Está seguro?" } %>
    <% end %>
  </div>
<% end %>

app/views/free_skates/edit.html.erb
<!-- lib/templates/erb/scaffold/edit.html.erb.tt -->

<div class="container mx-auto my-8 px-4", aling="center">
  <div class="max-w-xl mx-auto">
    <h1 class="text-2xl font-bold mb-6">Editar Free Skate</h1>

    <%= render 'form', free_skate: @free_skate %>
  </div>
</div>

app/views/free_skates/index.html.erb
<!-- lib/ /erb/scaffold/index.html.erb.tt -->

<div class="container mx-auto my-8 px-4">
  <div class="flex justify-between items-center mb-4">
    <h1 class="text-2xl font-semibold">Free Skates</h1>

    <% if @free_skates.exists? %>
      <%= link_to 'Nuevo', new_free_skate_path, class: "btn btn-success" %>
    <% end %>
  </div>

  <% if @free_skates.exists? %>
    <div class="bg-white rounded shadow">
      <table class="w-full table-hover">
        <thead>
          <tr>
            <th class="p-3 uppercase text-left text-xs text-gray-700">Description</th>

            <th class="p-3 uppercase text-left text-xs text-gray-700">Actions</th>
          </tr>
        </thead>

        <tbody>
        <% @free_skates.each do |free_skate| %>
          <tr class="group border-t border-gray-400 hover:bg-gray-100">
                          <td class="p-3"><%= free_skate.description %></td>
            
            <td>
              <%= link_to "Detalles", free_skate, class: "btn btn-info" %>
              <%= link_to "Editar", edit_free_skate_path(free_skate), class: "btn btn-primary" %>
     	      <td><%= link_to 'Eliminar', free_skate, class: "btn btn-danger" ,  method: :delete, data: { confirm: 'Está seguro?' } %></td>

            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>

  <% else %>
    <div class="bg-white rounded shadow flex items-center justify-between p-8">
      <div class="flex-1 text-center", align="center">
        <p class="text-xl font-semibold mb-4"> Crea tu primera Free Skate</p>
      <%= link_to 'Nuevo', new_free_skate_path, class: "btn btn-primary" %>
      </div>
    </div>
  <% end %>
</div>

app/views/free_skates/new.html.erb
<!-- lib/templates/erb/scaffold/new.html.erb.tt -->

<div class="container mx-auto my-8 px-4",aling="center">
  <div class="max-w-xl mx-auto">
    <h1 class="text-2xl font-bold mb-6">New Free Skate</h1>
    <%= link_to '< Volver', free_skates_path, class: "link" %></br></br>
    <%= render 'form', free_skate: @free_skate %>
  </div>
</div>

app/views/free_skates/show.html.erb
<!-- lib/templates/erb/scaffold/show.html.erb.tt -->

<div class="container", aling="center">
<div class="card border-primary mb-3">
<div class="card">
  <div class="card-header">
    Detalles
  </div>
  <div class="card-body">
    <div class="container mx-auto my-8 px-4">
            <p class="text-lg font-semibold">Description:</p>
      <p class="leading-normal"><%= @free_skate.description %></p>

            <div class="flex items-center justify-start mt-6">
        <%= link_to 'Editar', edit_free_skate_path(@free_skate), class: "btn btn-info mr-4" %>
        <%= link_to '< Volver', free_skates_path, class: "btn btn-default" %>
      </div>
    </div>
    </div>
  </div>
  </div>