config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'home/index'
  resources :athletes
  resources :compulsory_figures
  resources :free_skates
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
end

app/models/athlete.rb
class Athlete < ApplicationRecord
  belongs_to :category
  belongs_to :free_skate
  belongs_to :compulsory_figure
end

app/controllers/athletes_controller.rb
class AthletesController < ApplicationController
  before_action :set_athlete, only: [:show, :edit, :update, :destroy]

  # GET /athletes
  # GET /athletes.json
  def index
    @athletes = Athlete.all
  end

  # GET /athletes/1
  # GET /athletes/1.json
  def show
  end

  # GET /athletes/new
  def new
    @athlete = Athlete.new
  end

  # GET /athletes/1/edit
  def edit
  end

  # POST /athletes
  # POST /athletes.json
  def create
    @athlete = Athlete.new(athlete_params)

    respond_to do |format|
      if @athlete.save
        format.html { redirect_to @athlete, notice: 'Athlete was successfully created.' }
        format.json { render :show, status: :created, location: @athlete }
      else
        format.html { render :new }
        format.json { render json: @athlete.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /athletes/1
  # PATCH/PUT /athletes/1.json
  def update
    respond_to do |format|
      if @athlete.update(athlete_params)
        format.html { redirect_to @athlete, notice: 'Athlete was successfully updated.' }
        format.json { render :show, status: :ok, location: @athlete }
      else
        format.html { render :edit }
        format.json { render json: @athlete.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /athletes/1
  # DELETE /athletes/1.json
  def destroy
    @athlete.destroy
    respond_to do |format|
      format.html { redirect_to athletes_url, notice: 'Athlete was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_athlete
      @athlete = Athlete.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def athlete_params
      params.require(:athlete).permit(:document, :name, :last_name, :date_bir, :year, :category_id, :free_skate_id, :compulsory_figure_id)
    end
end

app/helpers/athletes_helper.rb
module AthletesHelper
end

app/views/athletes/_form.html.erb
<!-- lib/templates/erb/scaffold/_form.html.erb.tt -->

<%= form_with(model: athlete) do |form| %>
  <%= render "error_messages", resource: form.object %>

  <div class="mb-6">

    <%= form.label :document, class: "label" %>
    <%= form.number_field :document, class: "input" , class: "form-control" %>

  </div>

  <div class="mb-6">

    <%= form.label :name, class: "label" %>
    <%= form.text_field :name, class: "input", class: "form-control" %>

  </div>

  <div class="mb-6">

    <%= form.label :last_name, class: "label" %>
    <%= form.text_field :last_name, class: "input" , class: "form-control" %>

  </div>

  <div class="mb-6">

    <%= form.label :date_bir, class: "label" %>
    <%= form.date_field :date_bir, class: "form-control"  %>

  </div>

  <div class="mb-6">

    <%= form.label :year, class: "label" %>
    <%= form.number_field :year, class: "input" , class: "form-control" %>

  </div>

  <div class="row">
    <div class="form-group col-4">
      <%= form.label :category_id,"Categoría" %>
      <%= form.select(:category_id, Category.all.collect {|u| [u.description, u.id]}, :prompt => 'Select') %>
    </div>

    <div class="form-group col-4">
      <%= form.label :free_skate_id, "Nivel Libre" %>
      <%= form.select(:free_skate_id, FreeSkate.all.collect {|u| [u.description, u.id]}, :prompt => 'Select') %>
    </div>

    <div class="form-group col-4">
      <%= form.label :compulsory_figure_id, "Nivel Escuela" %>
      <%= form.select(:compulsory_figure_id, CompulsoryFigure.all.collect {|u| [u.description, u.id]}, :prompt => 'Select') %>
    </div>

  <div class="mb-6 flex justify-between items-center">
    <%= form.button class: "btn btn-primary" %>

    <% if form.object.persisted? %>
      <%= link_to 'Eliminar', form.object, class: "btn btn-danger", method: :delete, data: { remote: true, confirm: "Está seguro?" } %>
    <% end %>
  </div>
<% end %>

<script type="text/javascript">
  $(document).ready(function() {
      $('select').select2({
      	    width: 325
      });
  });

</script>

app/views/athletes/edit.html.erb
<!-- lib/templates/erb/scaffold/edit.html.erb.tt -->

<div class="container mx-auto my-8 px-4", aling="center">
  <div class="max-w-xl mx-auto">
    <h1 class="text-2xl font-bold mb-6 text-center">Editar Atleta</h1>
    <%= link_to '< Volver', athletes_path, class: "link" %></br></br>
    <%= render 'form', athlete: @athlete %>
  </div>
</div>

app/views/athletes/index.html.erb
<!-- lib/ /erb/scaffold/index.html.erb.tt -->

<div class="container mx-auto my-8 px-4">
  <div class="flex justify-between items-center mb-4">
    <h1 class="text-2xl font-semibold text-center">Atletas</h1>

    <% if @athletes.exists? %>
    <%= link_to 'Nuevo', new_athlete_path, class: "btn btn-success" %>
    <% end %>
  </div>

  <% if @athletes.exists? %>
  <div class="bg-white rounded shadow">
    <table id="athlete" class="display w-full table-hover" style="width:100%">
      <thead>
        <tr>
          <th class="p-3 uppercase text-left text-xs text-gray-700">Documento</th>
          <th class="p-3 uppercase text-left text-xs text-gray-700">Nombre</th>
          <th class="p-3 uppercase text-left text-xs text-gray-700">Apellido</th>
          <th class="p-3 uppercase text-left text-xs text-gray-700">Categoría</th>
          <th class="p-3 uppercase text-left text-xs text-gray-700">Free skate</th>
          <th class="p-3 uppercase text-left text-xs text-gray-700">Compulsory figure</th>

          <th class="p-3 uppercase text-left text-xs text-gray-700">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% @athletes.each do |athlete| %>
        <tr class="group border-t border-gray-400 hover:bg-gray-100">
          <td class="p-3"><%= athlete.document %></td>
          <td class="p-3"><%= athlete.name %></td>
          <td class="p-3"><%= athlete.last_name %></td>
          <td class="p-3"><%= athlete.category.description %></td>
          <td class="p-3"><%= athlete.free_skate.description %></td>
          <td class="p-3"><%= athlete.compulsory_figure.description %></td>
          <td class="p-3">
            <%= link_to "Detalles", athlete, class: "btn btn-info" %>
            <%= link_to "Editar", edit_athlete_path(athlete), class: "btn btn-primary" %>
         
            <%= link_to 'Eliminar', athlete, class: "btn btn-danger" ,  method: :delete, data: { confirm: 'Está seguro?' } %>
          </td>


        </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <% else %>
  <div class="bg-white rounded shadow flex items-center justify-between p-8">
    <div class="flex-1 text-center", align="center">
      <p class="text-xl font-semibold mb-4"> Crea tu primera Atleta</p>
      <%= link_to 'Nuevo', new_athlete_path, class: "btn btn-primary" %>
    </div>
  </div>
  <% end %>
</div>
<script type="text/javascript">

  $('#athlete').DataTable();

</script>

app/views/athletes/new.html.erb
<!-- lib/templates/erb/scaffold/new.html.erb.tt -->

<div class="container mx-auto my-8 px-4",aling="center">
  <div class="max-w-xl mx-auto">
    <h1 class="text-2xl font-bold mb-6 text-center"> Nueva Atleta</h1>
    <%= link_to '< Volver', athletes_path, class: "link" %></br></br>
    <%= render 'form', athlete: @athlete %>
  </div>
</div>

app/views/athletes/show.html.erb
<!-- lib/templates/erb/scaffold/show.html.erb.tt -->

<div class="container", aling="center">
<div class="card border-primary mb-3">
<div class="card">
  <div class="card-header">
    Detalles
  </div>
  <div class="card-body">
    <div class="container mx-auto my-8 px-4">
            <p class="text-lg font-semibold">Document:</p>
      <p class="leading-normal"><%= @athlete.document %></p>

            <p class="text-lg font-semibold">Name:</p>
      <p class="leading-normal"><%= @athlete.name %></p>

            <p class="text-lg font-semibold">Last name:</p>
      <p class="leading-normal"><%= @athlete.last_name %></p>

            <p class="text-lg font-semibold">Date bir:</p>
      <p class="leading-normal"><%= @athlete.date_bir %></p>

            <p class="text-lg font-semibold">Year:</p>
      <p class="leading-normal"><%= @athlete.year %></p>

            <p class="text-lg font-semibold">Category:</p>
      <p class="leading-normal"><%= @athlete.category.description %></p>

            <p class="text-lg font-semibold">Free skate:</p>
      <p class="leading-normal"><%= @athlete.free_skate.description %></p>

            <p class="text-lg font-semibold">Compulsory figure:</p>
      <p class="leading-normal"><%= @athlete.compulsory_figure.description %></p>

            <div class="flex items-center justify-start mt-6">
        <%= link_to 'Editar', edit_athlete_path(@athlete), class: "btn btn-info mr-4" %>
        <%= link_to '< Volver', athletes_path, class: "btn btn-default" %>
      </div>
    </div>
    </div>
  </div>
  </div>